package GPStreet.DB.Mapping.Entity;
// Generated Jun 3, 2015 4:45:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GpstPages generated by hbm2java
 */
public class GpstPages  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set gpstGroupses = new HashSet(0);

    public GpstPages() {
    }

    public GpstPages(String name, String description, Set gpstGroupses) {
       this.name = name;
       this.description = description;
       this.gpstGroupses = gpstGroupses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGpstGroupses() {
        return this.gpstGroupses;
    }
    
    public void setGpstGroupses(Set gpstGroupses) {
        this.gpstGroupses = gpstGroupses;
    }




}


