package GPStreet.DB.Mapping.Entity;
// Generated Sep 1, 2015 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GpstLocations generated by hbm2java
 */
public class GpstLocations  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Double latitude;
     private Double longitude;
     private Set gpstTrackers = new HashSet(0);

    public GpstLocations() {
    }

	
    public GpstLocations(String name) {
        this.name = name;
    }
    public GpstLocations(String name, String description, Double latitude, Double longitude, Set gpstTrackers) {
       this.name = name;
       this.description = description;
       this.latitude = latitude;
       this.longitude = longitude;
       this.gpstTrackers = gpstTrackers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Set getGpstTrackers() {
        return this.gpstTrackers;
    }
    
    public void setGpstTrackers(Set gpstTrackers) {
        this.gpstTrackers = gpstTrackers;
    }




}


