package GPStreet.DB.Mapping.Entity;
// Generated Apr 29, 2016 11:12:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GpstProductTypes generated by hbm2java
 */
public class GpstProductTypes  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String description;
     private Set gpstProductses = new HashSet(0);

    public GpstProductTypes() {
    }

	
    public GpstProductTypes(String type) {
        this.type = type;
    }
    public GpstProductTypes(String type, String description, Set gpstProductses) {
       this.type = type;
       this.description = description;
       this.gpstProductses = gpstProductses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGpstProductses() {
        return this.gpstProductses;
    }
    
    public void setGpstProductses(Set gpstProductses) {
        this.gpstProductses = gpstProductses;
    }




}


