package GPStreet.DB.Mapping.Entity;
// Generated Apr 29, 2016 11:12:33 AM by Hibernate Tools 4.3.1



/**
 * GpstProducts generated by hbm2java
 */
public class GpstProducts  implements java.io.Serializable {


     private Integer id;
     private GpstProductTypes gpstProductTypes;
     private String name;
     private String description;

    public GpstProducts() {
    }

	
    public GpstProducts(GpstProductTypes gpstProductTypes, String name) {
        this.gpstProductTypes = gpstProductTypes;
        this.name = name;
    }
    public GpstProducts(GpstProductTypes gpstProductTypes, String name, String description) {
       this.gpstProductTypes = gpstProductTypes;
       this.name = name;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GpstProductTypes getGpstProductTypes() {
        return this.gpstProductTypes;
    }
    
    public void setGpstProductTypes(GpstProductTypes gpstProductTypes) {
        this.gpstProductTypes = gpstProductTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


