package GPStreet.DB.Mapping.Entity;
// Generated Aug 26, 2015 5:38:34 PM by Hibernate Tools 4.3.1



/**
 * GpstLocations generated by hbm2java
 */
public class GpstLocations  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Double latitude;
     private Double longitude;

    public GpstLocations() {
    }

	
    public GpstLocations(String name) {
        this.name = name;
    }
    public GpstLocations(String name, String description, Double latitude, Double longitude) {
       this.name = name;
       this.description = description;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }




}


