package GPStreet.DB.Mapping.Entity;
// Generated Aug 26, 2015 5:38:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GpstTracker generated by hbm2java
 */
public class GpstTracker  implements java.io.Serializable {


     private Integer id;
     private GpstState gpstState;
     private int userId;
     private double latitude;
     private double longitude;
     private Date date;
     private double deviceId;
     private String notes;

    public GpstTracker() {
        
    }

	
    public GpstTracker(GpstState gpstState, int userId, double latitude, double longitude, double deviceId) {
        this.gpstState = gpstState;
        this.userId = userId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.deviceId = deviceId;
    }
    public GpstTracker(GpstState gpstState, int userId, double latitude, double longitude, Date date, double deviceId, String notes) {
       this.gpstState = gpstState;
       this.userId = userId;
       this.latitude = latitude;
       this.longitude = longitude;
       this.date = date;
       this.deviceId = deviceId;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GpstState getGpstState() {
        return this.gpstState;
    }
    
    public void setGpstState(GpstState gpstState) {
        this.gpstState = gpstState;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(double deviceId) {
        this.deviceId = deviceId;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


