package GPStreet.DB.Mapping.Entity;
// Generated Sep 1, 2015 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GpstState generated by hbm2java
 */
public class GpstState  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set gpstTrackers = new HashSet(0);

    public GpstState() {
    }

	
    public GpstState(String name) {
        this.name = name;
    }
    public GpstState(String name, String description, Set gpstTrackers) {
       this.name = name;
       this.description = description;
       this.gpstTrackers = gpstTrackers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGpstTrackers() {
        return this.gpstTrackers;
    }
    
    public void setGpstTrackers(Set gpstTrackers) {
        this.gpstTrackers = gpstTrackers;
    }




}


