package GPStreet.DB.Mapping.Entity;
// Generated Jun 3, 2015 4:45:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GpstGroups generated by hbm2java
 */
public class GpstGroups  implements java.io.Serializable {


     private Integer id;
     private String groupname;
     private String groupdesc;
     private Set gpstPageses = new HashSet(0);

    public GpstGroups() {
    }

    public GpstGroups(String groupname, String groupdesc, Set gpstPageses) {
       this.groupname = groupname;
       this.groupdesc = groupdesc;
       this.gpstPageses = gpstPageses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public String getGroupdesc() {
        return this.groupdesc;
    }
    
    public void setGroupdesc(String groupdesc) {
        this.groupdesc = groupdesc;
    }
    public Set getGpstPageses() {
        return this.gpstPageses;
    }
    
    public void setGpstPageses(Set gpstPageses) {
        this.gpstPageses = gpstPageses;
    }




}


